### ISSUE TITLE
The CRC bits calculation in DS1CA_polar_encoder.m might be incorrect

### ISSUE THREAD

**Issue by zpan008** [robmaunder/polar-3gpp-matlab#10]
The CRC bits by the below code don't match those calculated using other ways:

```
% Generate the CRC bits.
G_P = get_crc_generator_matrix(A+P,crc_polynomial_pattern);
crc_bits = mod([ones(1,P),a]*G_P,2);
```
If these lines are changed to either:
```
% Generate the CRC bits.
G_P = get_crc_generator_matrix(A,crc_polynomial_pattern);
crc_bits = mod(a*G_P,2);
```
or

```
% Generate the CRC bits.
G_P = get_crc_generator_matrix(A+P,crc_polynomial_pattern);
crc_bits = mod([zeors(1,P),a]*G_P,2);
```
the results will match. The first method is used in other encoders (DCA, PCCA etc).

**Comment by robmaunder** [comment]
@zpan008 - I'm not sure that this is a bug. DS1CA_polar_encoder.m is used in the PDCCH channel, which has a ones-initialised CRC, as described in Section 7.3.2 of 3GPP TS 38.212. By contrast, the PBCH and PUCCH/PUSCH channel do not use a ones-initialised CRC, as described in Sections 7.1.3, 6.3.1.2.1 and 6.3.2.2.1 of 3GPP TS 38.212.

**Comment by zpan008** [comment]
Ah, that explains. I have missed that completely. Many thanks.
